# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_order_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_order(object):
    def setupUi(self, Form_order):
        Form_order.setObjectName("Form_order")
        Form_order.resize(692, 423)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_order)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form_order)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_order_one_c_id = QtWidgets.QLineEdit(Form_order)
        self.lineEdit_order_one_c_id.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_order_one_c_id.setObjectName("lineEdit_order_one_c_id")
        self.verticalLayout.addWidget(self.lineEdit_order_one_c_id)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add_row = QtWidgets.QPushButton(Form_order)
        self.pushButton_add_row.setObjectName("pushButton_add_row")
        self.horizontalLayout.addWidget(self.pushButton_add_row)
        self.pushButton_delete_row = QtWidgets.QPushButton(Form_order)
        self.pushButton_delete_row.setObjectName("pushButton_delete_row")
        self.horizontalLayout.addWidget(self.pushButton_delete_row)
        self.pushButton_save_and_close = QtWidgets.QPushButton(Form_order)
        self.pushButton_save_and_close.setObjectName("pushButton_save_and_close")
        self.horizontalLayout.addWidget(self.pushButton_save_and_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_characteristics_in_order = QtWidgets.QTableWidget(Form_order)
        self.tableWidget_characteristics_in_order.setObjectName("tableWidget_characteristics_in_order")
        self.tableWidget_characteristics_in_order.setColumnCount(0)
        self.tableWidget_characteristics_in_order.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_characteristics_in_order)

        self.retranslateUi(Form_order)
        QtCore.QMetaObject.connectSlotsByName(Form_order)

    def retranslateUi(self, Form_order):
        _translate = QtCore.QCoreApplication.translate
        Form_order.setWindowTitle(_translate("Form_order", "Заказ"))
        self.label.setText(_translate("Form_order", "Номер заказа:"))
        self.pushButton_add_row.setText(_translate("Form_order", "Добавить"))
        self.pushButton_delete_row.setText(_translate("Form_order", "Удалить"))
        self.pushButton_save_and_close.setText(_translate("Form_order", "Сохранить и закрыть"))
