"""initial

Revision ID: 7d13552000b4
Revises: 
Create Date: 2022-05-21 11:27:24.026006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d13552000b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Knitting_machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Nomenclature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('time_references', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Specifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['Nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['Nomenclature.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['Specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    op.drop_table('Specifications')
    op.drop_table('Nomenclature')
    op.drop_table('Knitting_machines')
    # ### end Alembic commands ###
